export {default as Navbar} from "./Navbar"
export {default as Hero} from "./Hero"
export {default as GetStarted} from "./GetStarted"
export {default as Stats} from "./Stats"
export {default as Businss} from "./Businss"
export {default as Billing} from "./Billing"
export {default as Testimonials} from "./Testimonials"
export {default as Clients} from "./Clients"
export {default as CardDeal} from "./CardDeal"
export {default as CTA} from "./CTA"
export {default as Footer} from "./Footer"

